local constants = {

	BLOOD_TYPES     = JsonUtils:LoadJSON('gcs_core/data/blood_type.json'),
	COMPONENTS      = JsonUtils:LoadJSON('gcs_core/data/components.json'),
	DISEASE         = JsonUtils:LoadJSON('gcs_core/data/disease.json'),
	GASOLINE        = JsonUtils:LoadJSON('gcs_core/data/gasoline.json'),
	PED_PROP        = JsonUtils:LoadJSON('gcs_core/data/ped_prop_defs.json'),
	PED_TORSO       = JsonUtils:LoadJSON('gcs_core/data/ped_torso_defs.json'),
	SEATS           = JsonUtils:LoadJSON('gcs_core/data/seats.json'),
	VEHICLE_PRICE   = JsonUtils:LoadJSON('gcs_core/data/vehicle_prices.json'),
	VEHICLE_STORAGE = JsonUtils:LoadJSON('gcs_core/data/vehicle_storage.json'),
	WEAPONS         = JsonUtils:LoadJSON('gcs_core/data/weapons.json'),
	AIR_MASTS       = JsonUtils:LoadJSON('gcs_core/data/world_air_masts.json'),
	ANTENNAS        = JsonUtils:LoadJSON('gcs_core/data/world_antennas.json'),
	WORLD_ATM       = JsonUtils:LoadJSON('gcs_core/data/world_atms.json'),
	BINS_DUMPSTERS  = JsonUtils:LoadJSON('gcs_core/data/world_bins_dumpsters.json'),
	BUS_STOP_SIGN   = JsonUtils:LoadJSON('gcs_core/data/world_bus_stop_signs.json'),
	BUS_STOPS       = JsonUtils:LoadJSON('gcs_core/data/world_bus_stops.json'),
	DART_DISCS      = JsonUtils:LoadJSON('gcs_core/data/world_dart_discs.json'),
	EXTRA_PHONES    = JsonUtils:LoadJSON('gcs_core/data/world_extra_phones.json'),
	FIRE_HYDRANT    = JsonUtils:LoadJSON('gcs_core/data/world_fire_hydrant_driser.json'),
	FRUIT_STANDS    = JsonUtils:LoadJSON('gcs_core/data/world_fruit_stands.json'),
	GAS_PUMPS       = JsonUtils:LoadJSON('gcs_core/data/world_gas_pumps.json'),
	HARVEST_FIELD   = JsonUtils:LoadJSON('gcs_core/data/world_harvest_fields.json'),
	JUKEBOXES       = JsonUtils:LoadJSON('gcs_core/data/world_jukeboxes.json'),
	LETTER_BOXES    = JsonUtils:LoadJSON('gcs_core/data/world_letter_boxes.json'),
	MOBILE_MASTS    = JsonUtils:LoadJSON('gcs_core/data/world_mobile_masts.json'),
	NEWS_PAPER      = JsonUtils:LoadJSON('gcs_core/data/world_news_paper_dispensers.json'),
	PARK_METERS     = JsonUtils:LoadJSON('gcs_core/data/world_park_meters.json'),
	POST_BOXES      = JsonUtils:LoadJSON('gcs_core/data/world_post_boxes.json'),
	PUBLIC_PHONE    = JsonUtils:LoadJSON('gcs_core/data/world_public_phones.json'),
	RADIO_TOWERS    = JsonUtils:LoadJSON('gcs_core/data/world_radio_towers.json'),
	RECYCLE_BINS    = JsonUtils:LoadJSON('gcs_core/data/world_recycle_bins.json'),
	WORLD_SEATS     = JsonUtils:LoadJSON('gcs_core/data/world_seats.json'),
	TELESCOPES      = JsonUtils:LoadJSON('gcs_core/data/world_telescopes.json'),
	VENDING_MACHINE = JsonUtils:LoadJSON('gcs_core/data/world_vending_machines.json'),

}

return constants
